version: '3.8'

services:
  php-fpm:
    container_name: php-container-siwar
    restart: always
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/var/www/html
    networks:
      vpcbrsiwar:
        ipv4_address: 10.5.1.5
  nginx:
    container_name: nginx-container-siwar
    restart: always
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "8282:80"
    networks:
      vpcbrsiwar:
        ipv4_address: 10.5.1.6
  mysql:
    image: mysql:8
    container_name: mysql-container-siwar
    ports:
      - "3305:3305"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    networks:
      vpcbrsiwar:
        ipv4_address: 10.5.1.7
  phpmyadmin:
    container_name: phpmyadmin-container-siwar
    image: phpmyadmin
    restart: always
    ports:
      - "8181:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      vpcbrsiwar:
        ipv4_address: 10.5.1.8
    depends_on:
      - php-fpm
      - mysql
      - nginx

  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
volumes:

  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###
  database:
networks:
  vpcbrsiwar:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.1.0/16